### ISSUE TITLE
Testing op-admin-dashboard

### ISSUE THREAD

**Issue by swastis10** [e-mission/op-admin-dashboard#21] opened 2023-03-16 22:21 UTC
I have started testing op-admin-dashboard. I checked out `dev` branch found [here](https://github.com/e-mission/op-admin-dashboard/tree/dev).

I loaded data in the dashboard using the script found [here](https://github.com/e-mission/em-public-dashboard/blob/main/viz_scripts/docker/load_mongodump.sh). The tar files loaded were -

- vail_2023-01-01.tar
- 4c_2023-01-01.tar
- sc_2023-01-01.tar
- fc_2023-01-01.tar

The dashboard has started to look something like the screenshot attached below.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/124807088/225765722-428cf750-9070-4eb5-b23b-f216e29d8713.png">

**Comment by AlirezaRa94** [comment] 2023-03-24 06:36
@shankari 
I'm happy with the first approach as well.

Another point to mention about the token page is that it displays all the tokens available in the database, including the new ones. It also exports all of them, which I believe is not the intended behavior.
We could either show only the new tokens or if we need to include the existing ones, we should separate them.

**Comment by shankari** [comment] 2023-03-24 17:14
@AlirezaRa94 I think it would be good to show both but separate them
that way, if people forget to hit the "save" button, they are not like "why aren't the new tokens working"? They can see the loaded tokens and understand why. You might want to make the existing tokens page display in reverse cron, though so the newly added tokens will show up first instead of making people paginate all the way to the end.

**Comment by shankari** [comment] 2023-03-25 03:21
@AlirezaRa94 production dockerfile does not work; container continually fails restart with

```
Connecting to database URL db
emission/tests/data/real_examples/shankari_2015-07-22
Loading file emission/tests/data/real_examples/shankari_2015-07-22
After registration, test_july_22 -> 28828dff-a670-4c49-878e-96d9f6d95473
Finished loading 0 entries into the usercache and 1906 entries into the timeseries
Traceback (most recent call last):
  File "app_sidebar_collapsible.py", line 20, in <module>
    from utils.db_utils import query_uuids, query_confirmed_trips
ModuleNotFoundError: No module named 'utils'
```

**Comment by AlirezaRa94** [comment] 2023-03-25 05:36
@shankari I didn't say that the production version of the docker-compose is ready for your testing!

**Comment by swastis10** [comment] 2023-04-05 21:53
@AlirezaRa94 , I have created a test App client on NREL AWS console with the following settings:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/124807088/230218735-1446f985-edc9-4caf-8d74-e9f851872194.png">
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/124807088/230218803-4804b2ba-ff67-4565-af70-cd1da534edf4.png">
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/124807088/230218948-aa5eb654-9590-403a-ab63-57090c1e4641.png">

In Config.py, my configs are as follows:
```
class CognitoConfig:
    CLIENT_ID = '5e5c3qdvq6so59alca304f9tv3'
    CLIENT_SECRET = '8htj7mvrnuf34ik6khi7a74qsdvgj11uaja7pmkb4a8oheb1olt'

    REDIRECT_URL = 'http://localhost:8050'
    TOKEN_ENDPOINT = 'https://openpath-stage.auth.us-west-2.amazoncognito.com/oauth2/token'

    USER_POOL_ID = 'us-west-2_O184jYo10'
    REGION = 'us-west-2'
    AUTH_URL = 'https://openpath-stage.auth.us-west-2.amazoncognito.com/login?response_type=code&client_id=5e5c3qdvq6so59alca304f9tv3&redirect_uri=http://localhost:8050'
```

Even then, I am getting the following error.
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/124807088/230219406-9e470c61-939d-450a-8660-c0f45b7c9733.png">

**Comment by shankari** [comment] 2023-04-05 22:33
@swastis10 are there any error logs? For that matter, where do you see logs in a dash app?

**Comment by AlirezaRa94** [comment] 2023-04-06 01:31
@swastis10 I can sign in without any problems with the config that you have provided. Can you check the config.py file inside the docker container and see if it is the same?

**Comment by shankari** [comment] 2023-04-17 15:25
Closing this for now since portmanteau issues are hard to debug and resolve

**Closed as completed by shankari** 2023-04-17 15:25 UTC
